/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/job-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all job applications
         * @description Retrieve a list of all job applications in the system.
         */
        get: operations["JobApplicationsController_findAll"];
        put?: never;
        /**
         * Create a new job application
         * @description Add a new job application to the system.
         */
        post: operations["JobApplicationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a job application by ID
         * @description Retrieve a specific job application by its unique identifier.
         */
        get: operations["JobApplicationsController_findById"];
        put?: never;
        post?: never;
        /**
         * Delete a job application
         * @description Remove a job application from the system by its unique identifier.
         */
        delete: operations["JobApplicationsController_delete"];
        options?: never;
        head?: never;
        /**
         * Update a job application
         * @description Update the details of an existing job application.
         */
        patch: operations["JobApplicationsController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JobApplicationEntity: {
            /**
             * @description Unique identifier
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            id: string;
            /**
             * @description Company name
             * @example Google
             */
            company: string;
            /**
             * @description Position title
             * @example Backend Engineer
             */
            position: string;
            /**
             * @description Current status of the application
             * @example APPLIED
             */
            status: string;
            /**
             * Format: date-time
             * @description Date the application was submitted
             * @example 2026-01-15T00:00:00.000Z
             */
            appliedAt: string;
            /**
             * @description Link to the job posting
             * @example https://jobs.example.com/123
             */
            url?: string | null;
            /**
             * @description Additional notes
             * @example Referred by a friend
             */
            notes?: string | null;
            /**
             * Format: date-time
             * @description Timestamp when the record was created
             * @example 2026-01-15T10:00:00.000Z
             */
            createdAt: string;
        };
        ErrorResponseEntity: {
            /**
             * @description HTTP status code
             * @example 404
             */
            status: number;
            /**
             * @description Error message
             * @example Job application with ID ... not found
             */
            message: string;
            /**
             * @description Time the error occurred
             * @example 2026-09-09T12:34:56.789Z
             */
            timestamp: string;
            /**
             * @description Request path that caused the error
             * @example /api/job-applications/abc
             */
            path: string;
        };
        CreateJobApplicationDto: {
            /**
             * @description Company name
             * @example Google
             */
            company: string;
            /**
             * @description Position title
             * @example Backend Engineer
             */
            position: string;
            /**
             * @description Current status of the application
             * @example APPLIED
             */
            status: string;
            /**
             * @description Date the application was submitted (ISO 8601)
             * @example 2026-01-15
             */
            appliedAt: string;
            /**
             * Format: uri
             * @description Link to the job posting
             * @example https://jobs.example.com/123
             */
            url?: string;
            /**
             * @description Additional notes
             * @example Referred by a friend
             */
            notes?: string;
        };
        UpdateJobApplicationDto: {
            /**
             * @description Company name
             * @example Google
             */
            company?: string;
            /**
             * @description Position title
             * @example Backend Engineer
             */
            position?: string;
            /**
             * @description Current status of the application
             * @example APPLIED
             */
            status?: string;
            /**
             * @description Date the application was submitted (ISO 8601)
             * @example 2026-01-15
             */
            appliedAt?: string;
            /**
             * Format: uri
             * @description Link to the job posting
             * @example https://jobs.example.com/123
             */
            url?: string;
            /**
             * @description Additional notes
             * @example Referred by a friend
             */
            notes?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    JobApplicationsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of job applications retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplicationEntity"][];
                };
            };
        };
    };
    JobApplicationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobApplicationDto"];
            };
        };
        responses: {
            /** @description Job application created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplicationEntity"];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    JobApplicationsController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job application ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job application found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplicationEntity"];
                };
            };
            /** @description Invalid UUID format. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description Job application not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    JobApplicationsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job application ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job application deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplicationEntity"];
                };
            };
            /** @description Invalid UUID format. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description Job application not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    JobApplicationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job application ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJobApplicationDto"];
            };
        };
        responses: {
            /** @description Job application updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplicationEntity"];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description Job application not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
}
